DROP TABLE IF EXISTS skills_events;
DROP TABLE IF EXISTS skill;
DROP TABLE IF EXISTS roles_users;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS events_users;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS user;
